# Generated by Django 5.1.7 on 2025-03-28 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=132)),
                ('Email', models.EmailField(max_length=254)),
                ('Telephone', models.CharField(max_length=132)),
                ('Adresse', models.CharField(max_length=64)),
                ('Sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin ')], max_length=1)),
                ('Age', models.CharField(max_length=12)),
                ('Ville', models.CharField(max_length=32)),
                ('Code_postal', models.CharField(max_length=16)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Eng_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=32)),
                ('Quantity', models.IntegerField()),
                ('Prix_unitaire', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.client')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='Thefac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_date_time', models.DateTimeField(auto_now_add=True)),
                ('Total', models.DecimalField(decimal_places=4, max_digits=100000)),
                ('Last_updated_date', models.DateTimeField(null=True)),
                ('Payer', models.BooleanField(default=False)),
                ('Thefac_type', models.CharField(choices=[('R', 'RECU'), ('P', 'FACTURE_INCERTAINE'), ('F', 'FACTURE')], max_length=1)),
                ('Commentaires', models.TextField(blank=True, max_length=2000, null=True)),
                ('Eng_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.client')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
    ]
