# Generated by Django 5.1.7 on 2025-04-06 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thefac',
            options={'verbose_name': 'Thefac', 'verbose_name_plural': 'Thefacs'},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='client',
            new_name='thefac',
        ),
        migrations.RenameField(
            model_name='thefac',
            old_name='client_date_time',
            new_name='thefac_date_time',
        ),
    ]
